---
title: "PS811 Portfolio"
author: "Valeriia Umanets"
output:
  html_document: 
    toc: true ## table of contents
    code_folding: hide
---
```{r setup, include=FALSE}
## Defaults for R chunks
knitr::opts_chunk$set(echo = TRUE, ## echo = TRUE means code will show
                      warning=FALSE, ## supress warnings and messages from R
                      message=FALSE,
                      fig.path='Figs/', ## where to save figures
                      fig.height = 3, ## default figure size (can differ in each chunk)
                      fig.width = 3)

## Add any R packages you require. 
## Here are some we will use in 811:
requires <- c("tidyverse", ## tidyverse includes dplyr and ggplot2
              "magrittr",
              "foreign",
              "readstata13",
              "here")

## Install any you don't have
to_install <- c(requires %in% rownames(installed.packages()) == FALSE)
install.packages(c(requires[to_install], "NA"), repos = "https://cloud.r-project.org/" )

## Load all required R packages
library(tidyverse)
library(ggplot2); theme_set(theme_minimal())
library(magrittr)
library(here)
```
<!-- The above header sets everything up. -->





### Research Interests
I am interested in elections in non-democratic political regimes and political economy of repressions in Eastern Europe and Eurasia. 

---
### Questions I hope to answer
What is the role of type of electoral system and form of governance is the success of hegemonic parties in electoral authoritarian regimes? When and what type of repressions do autocrats apply in such regimes? 
---

### Methods
I am interested in cluster analysis, content analysis, and longitudinal analysis. 

---

### Relevant data
- The Authoritarian Regimes Dataset (ARD) is a comprehensive dataset on authoritarian regimes in the world between 1972-2014. It distinguishes different forms of authoritarian regimes by their institutional setups. ([data](https://sites.google.com/site/authoritarianregimedataset/home)) 
- The Database of Political Institutions (DPI) presents institutional and electoral results data such as measures of checks and balances, tenure and stability of the government, identification of party affiliation and ideology, and fragmentation of opposition and government parties in the legislature. ([data](https://publications.iadb.org/handle/11319/7408))
- V-Dem database is data with over 350 indicators on democratic and authoritarian systems across the world from 1900 to the present ([data](https://www.v-dem.net))

<!-- 
Valeriia,
These datasets look like solid options. They all seem quite large, so your key task will be to select a few variables of interests. 
Try writing a few lines of R code that loads these data from their URL and then uses the select() from dplyr to trim it down to the columns you want. Make sure to include any ID columns. 
If the files are very large, you may want to make a short .R script that loads from the URL, selects the variables you want, and then saves your new, smaller data file in a folder called "data" (make sure to save this script in your 811 folder, commit it, and push it). This portfolio page can then load this smaller data file from that folder using here(data/YourNewDataFile).
Best,
Devin
-->

